import React from "react";

const page = () => {

}

export default page


/* MAKE THIS A PROTECTED PAGE, MAKE QUESTIONS APPEAR, 
WRITE CODE TO ASK USERS TO CHOOSE THEIR ROLE (STUDENT OR TEACHER), 
DASHBOARD NEEDS TO INCLUDE THE CLASSES A STUDENT IS A PART OF AND GIVE 
OPTION TO CHOOSE WHAT SUBJECT THEY WANT TO WORK ON BASED ON THE CLASS */